



version: "3.5"

services:
    ### Database for Context Broker ###
    mongo-db:
        image: mongo:3.6
        hostname: mongo-db
        container_name: mongo
        expose:
            - "27017"
        ports:
            - 27017:27017
        networks:
            - default          
        command: --bind_ip_all --smallfiles
        volumes:
            - ${RAMP_PATH}/mongo:/data/db

    ### Context Broker ###
    orion:
        image: fiware/orion
        hostname: orion
        container_name: fiware-orion
        depends_on:
            - mongo-db
        networks:
            - default
        ports:
            - 1026:1026
        entrypoint: ["sh", "-c", "rm /tmp/contextBroker.pid; /usr/bin/contextBroker -fg -multiservice -dbhost mongo-db -corsOrigin __ALL -inReqPayloadMaxSize 2097152 -logLevel DEBUG"]
        #command:
        #    -dbhost mongo-db -corsOrigin __ALL -logLevel DEBUG -inReqPayloadMaxSize 2097152
        restart: always

    iot-agent:
        image: fiware/iotagent-ul:latest
        hostname: iot-agent
        container_name: fiware-iot-agent
        depends_on:
            - mongo-db
        networks:
            - default
        expose:
            - "4041"
            - "7896"
        ports:
            - "4041:4041"
            - "7896:7896"
        environment:
            - IOTA_CB_HOST=orion
            - IOTA_CB_PORT=1026
            - IOTA_NORTH_PORT=4041
            - IOTA_REGISTRY_TYPE=mongodb
            - IOTA_TIMESTAMP=true
            - IOTA_CB_NGSI_VERSION=v2
            - IOTA_AUTOCAST=true
            - IOTA_MONGO_HOST=mongo-db
            - IOTA_MONGO_PORT=27017
            - IOTA_MONGO_DB=iotagentul
            - IOTA_HTTP_PORT=7896
            - IOTA_MQTT_PORT=1883
            - IOTA_MQTT_HOST=130.188.160.83

            - IOTA_PROVIDER_URL=http://iot-agent:4041

    crate-db:
        image: crate:4.1.4
        hostname: crate-db
        command: crate -Cauth.host_based.enabled=false -Ccluster.name=rampcluster -Chttp.cors.enabled=false -Chttp.cors.allow-origin="*"
        environment:
            - CRATE_HEAP_SIZE=2g
        ports:
            # Admin UI
            - "4200:4200"
            # Transport protocol
            - "4300:4300"
            - "5432:5432"
        volumes:
            - ${RAMP_PATH}/cratedata:/data
        networks: 
            - default
        restart: always

    quantumleap:
        hostname: quantumleap
        image: smartsdk/quantumleap:latest
        depends_on:
            - crate-db
        container_name: fiware-quantumleap
        ports:
            - "8668:8668"
        environment:
            - CRATE_HOST=crate-db
            - CRATE_PORT=4200
            - USE_GEOCODING=True
        networks:
            - default

    ### Grafana dashboard ###
    grafana:
        image: grafana/grafana
        depends_on:
            - crate-db
        container_name: grafana
        hostname: grafana
        ports:
            - 3000:3000
        networks:
            - default
        volumes:
            - grafana-storage:/var/lib/grafana
            - ./provisioning:/etc/grafana/provisioning/
        restart: always

    # Identity Management
    mysql:
        image: mysql/mysql-server:5.7
        ports:
            - '3306:3306'
        networks:
            idm_network:
                ipv4_address: 172.18.1.5
        environment:
           - MYSQL_ROOT_PASSWORD=idm
           - MYSQL_ROOT_HOST=%

    fiware-idm:
        image: fiware/idm
          
        ports:
            - '1024:1024'
            - '443:443'
        networks:
            idm_network:
                ipv4_address: 172.18.1.6
        environment:
            - IDM_DB_HOST=mysql
            - IDM_DB_PASS=idm

volumes:
    mongo-db:
    cratedata:
    grafana-storage:
    vol-mysql:

networks:
    default:
        ipam:
            config:
                - subnet: 172.19.1.0/24

    idm_network:
#        driver: bridge
        ipam:
            config:
                - subnet: 172.18.1.0/24
                  gateway: 172.18.1.1
