Document: rampiot
Title: Debian rampiot Manual
Author: <insert document author here>
Abstract: This manual describes what rampiot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rampiot/rampiot.sgml.gz

Format: postscript
Files: /usr/share/doc/rampiot/rampiot.ps.gz

Format: text
Files: /usr/share/doc/rampiot/rampiot.text.gz

Format: HTML
Index: /usr/share/doc/rampiot/html/index.html
Files: /usr/share/doc/rampiot/html/*.html
